// <auto-generated />
namespace DS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class v3AddedMenuModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v3AddedMenuModel));
        
        string IMigrationMetadata.Id
        {
            get { return "201711051612436_v3 Added Menu Model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
